### ISSUE TITLE
Error with username in channel

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#13]
```
WARN There was an error sending a matrix event SyntaxError: Invalid regular expression: /Smiley  =)/: Unmatched ')'
WARN There was an error sending a matrix event     at DiscordBot.HandleMentions (/root/matrix-appservice-discord/build/src/bot.js:228:33)
WARN There was an error sending a matrix event     at DiscordBot.MatrixEventToEmbed (/root/matrix-appservice-discord/build/src/bot.js:132:35)
WARN There was an error sending a matrix event     at DiscordBot.<anonymous> (/root/matrix-appservice-discord/build/src/bot.js:148:32)
WARN There was an error sending a matrix event     at next (native)
WARN There was an error sending a matrix event     at fulfilled (/root/matrix-appservice-discord/build/src/bot.js:4:58)
WARN There was an error sending a matrix event     at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by Half-Shot** [comment]
Looks like I might not be escaping these properly. I'll take a look

**Comment by turt2live** [comment]
For reference: This is preventing messages from being sent. The error only occurs when a matrix message is received. Discord -> Matrix is fine

**Comment by turt2live** [comment]
Update: this seemingly breaks all outbound messages to discord, even for unrelated channels/guilds.

**Comment by Half-Shot** [comment]
This appears to be fixed. Closing
