### ISSUE TITLE
Content upload error not handled when homeserver upload limit is too low

### ISSUE THREAD

**Issue by johnyhlee** [Half-Shot/matrix-appservice-discord#135]
I had configured my homeserver to have a file upload limit smaller than that of Discord (8MB), and kept experiencing crashes of the bridge from time to time. It turns out that this happened when someone uploaded a file larger than my homeserver's limit but smaller than 8MB:

```
ERR! UploadContent  Failed to upload content:
ERR! UploadContent  Failed to upload content:
ERR! UploadContent %s { SyntaxError: Unexpected token < in JSON at position 0
ERR! UploadContent     at Object.parse (native)
ERR! UploadContent     at /root/matrix-appservice-discord/node_modules/matrix-js-sdk/lib/http-api.js:719:37
ERR! UploadContent     at /root/matrix-appservice-discord/node_modules/matrix-js-sdk/lib/http-api.js:677:21
ERR! UploadContent     at Request._callback (/root/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/client-factory.js:75:13)
ERR! UploadContent     at Request.self.callback (/root/matrix-appservice-discord/node_modules/request/request.js:186:22)
ERR! UploadContent     at emitTwo (events.js:106:13)
ERR! UploadContent     at Request.emit (events.js:191:7)
ERR! UploadContent     at Request.<anonymous> (/root/matrix-appservice-discord/node_modules/request/request.js:1163:10)
ERR! UploadContent     at emitOne (events.js:96:13)
ERR! UploadContent     at Request.emit (events.js:188:7)
ERR! UploadContent     at IncomingMessage.<anonymous> (/root/matrix-appservice-discord/node_modules/request/request.js:1085:12)
ERR! UploadContent     at IncomingMessage.g (events.js:292:16)
ERR! UploadContent     at emitNone (events.js:91:20)
ERR! UploadContent     at IncomingMessage.emit (events.js:185:7)
ERR! UploadContent     at endReadableNT (_stream_readable.js:978:12)
ERR! UploadContent     at _combinedTickCallback (internal/process/next_tick.js:80:11)
ERR! UploadContent     at process._tickCallback (internal/process/next_tick.js:104:9)
ERR! UploadContent   stack: 'SyntaxError: Unexpected token < in JSON at position 0\n    at Object.parse (native)\n    at /root/matrix-appservice-discord/node_modules/matrix-js-sdk/l
ib/http-api.js:719:37\n    at /root/matrix-appservice-discord/node_modules/matrix-js-sdk/lib/http-api.js:677:21\n    at Request._callback (/root/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/client-factory.js:75:13)\n    at Request.self.callback (/root/matrix-appservice-discord/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/root/matrix-appservice-discord/node_modules/request/request.js:1163:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/root/matrix-appservice-discord/node_modules/request/request.js:1085:12)\n    at IncomingMessage.g (events.js:292:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:978:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)',
ERR! UploadContent   httpStatus: 413 }
Unhandled rejection SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /root/matrix-appservice-discord/node_modules/matrix-js-sdk/lib/http-api.js:719:37
    at /root/matrix-appservice-discord/node_modules/matrix-js-sdk/lib/http-api.js:677:21
    at Request._callback (/root/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/client-factory.js:75:13)
    at Request.self.callback (/root/matrix-appservice-discord/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/matrix-appservice-discord/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/matrix-appservice-discord/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

This would sometimes cause my server to crash without warning. For now, I've increased the upload limit to the server, but either a warning in the setup instructions or more graceful error handling would be ideal.

Thank you!

**Comment by Half-Shot** [comment]
This would be fixed if we had https://github.com/matrix-org/matrix-doc/issues/1232. Until then I guess I will have to make a config option for it
