### ISSUE TITLE
Unable to use adminme script

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#168]
When running `npm run-script adminme -- -r '!XxXXxxxXxxXXX:amorgan.xyz' -u '@andrewm:amorgan.xyz' -p '100'` I get the following error log:

```
SyncApi.sync: starting with sync token null
Got push rules  
/sync error M_UNKNOWN: Internal server error                                                                                    
{ [M_UNKNOWN: Internal server error]
  errcode: 'M_UNKNOWN',
  name: 'M_UNKNOWN',
  message: 'Internal server error',                                       
  data: { errcode: 'M_UNKNOWN', error: 'Internal server error' },                                 
  httpStatus: 500 }
Starting keep-alive                                 
/home/ops/.matrix-appservice-discord/node_modules/olm/olm.js:19 
"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.insp
ect=function(){return"[Emscripten Module object]"}}else if(ma)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=
printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},a.readBinary=function(a){if("functi
on"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");z("object"===typeof a);return a},"undefined"!=
                                                                                                                ^

TypeError: Cannot set property 'access_token' of undefined
    at MatrixHttpApi._request (/home/ops/.matrix-appservice-discord/node_modules/matrix-js-sdk/lib/http-api.js:620:34)
    at MatrixHttpApi.requestOtherUrl (/home/ops/.matrix-appservice-discord/node_modules/matrix-js-sdk/lib/http-api.js:558:21)
    at MatrixHttpApi.request (/home/ops/.matrix-appservice-discord/node_modules/matrix-js-sdk/lib/http-api.js:443:21)
    at SyncApi._pokeKeepAlive (/home/ops/.matrix-appservice-discord/node_modules/matrix-js-sdk/lib/sync.js:892:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! matrix-appservice-discord@0.2.0-rc3 adminme: `node ./build/tools/adminme.js "-r" "!XxXXxxxXxxXXX:amorgan.xyz" "-u" "100"
```

Looks like an issue with Synapse perhaps?

**Comment by anoadragon453** [comment]
Issue explained here: https://github.com/Half-Shot/matrix-appservice-discord/issues/58
