### ISSUE TITLE
Multiple runs of npm start break database

### ISSUE THREAD

**Issue by anoadragon453** [Half-Shot/matrix-appservice-discord#22]
Running `npm start` initially works fine and the bot starts up. However killing the process and running `npm start` again causes the following error output, forcing a full recreation of the database to start correctly again:

```
WARN MatrixRoomHandler Skipping event due to age 13307669916 > 900000 
WARN MatrixRoomHandler Skipping event due to age 323627349 > 900000 
 
^C 
root@ubuntu:~/.matrix-appservice-discord# npm start 
 
> matrix-appservice-discord@0.0.1 start /root/.matrix-appservice-discord 
> npm run-script build && node ./build/src/discordas.js -p 9005 -c config.yaml 
 
 
> matrix-appservice-discord@0.0.1 build /root/.matrix-appservice-discord 
> tsc 
 
Loading config file /root/.matrix-appservice-discord/config.yaml 
ERR! DiscordStore Couldn't update database to schema 2 
ERR! DiscordStore Error: Error creating 'dm_rooms': Error: SQLITE_ERROR: table dm_rooms already exists 
ERR! DiscordStore     at db.runAsync.then.catch (/root/.matrix-appservice-discord/build/src/store.js:96:19) 
ERR! DiscordStore     at tryCatcher (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/util.js:16:23) 
ERR! DiscordStore     at Promise._settlePromiseFromHandler (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:512:31) 
ERR! DiscordStore     at Promise._settlePromise (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:569:18) 
ERR! DiscordStore     at Promise._settlePromise0 (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:614:10) 
ERR! DiscordStore     at Promise._settlePromises (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:689:18) 
ERR! DiscordStore     at Async._drainQueue (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/async.js:133:16) 
ERR! DiscordStore     at Async._drainQueues (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/async.js:143:10) 
ERR! DiscordStore     at Immediate.Async.drainQueues (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/async.js:17:14) 
ERR! DiscordStore     at runCallback (timers.js:672:20) 
ERR! DiscordStore     at tryOnImmediate (timers.js:645:5) 
ERR! DiscordStore     at processImmediate [as _immediateCallback] (timers.js:617:5) 
ERR! DiscordStore  { Error: Error creating 'dm_rooms': Error: SQLITE_ERROR: table dm_rooms already exists 
ERR! DiscordStore     at db.runAsync.then.catch (/root/.matrix-appservice-discord/build/src/store.js:96:19) 
ERR! DiscordStore     at tryCatcher (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/util.js:16:23) 
ERR! DiscordStore     at Promise._settlePromiseFromHandler (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:512:31) 
ERR! DiscordStore     at Promise._settlePromise (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:569:18) 
ERR! DiscordStore     at Promise._settlePromise0 (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:614:10) 
ERR! DiscordStore     at Promise._settlePromises (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:689:18) 
ERR! DiscordStore     at Async._drainQueue (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/async.js:133:16)
ERR! DiscordStore     at Async._drainQueues (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/async.js:143:10)
ERR! DiscordStore     at Immediate.Async.drainQueues (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/async.js:17:14)
ERR! DiscordStore     at runCallback (timers.js:672:20)
ERR! DiscordStore     at tryOnImmediate (timers.js:645:5)
ERR! DiscordStore     at processImmediate [as _immediateCallback] (timers.js:617:5)
ERR! DiscordStore   stack: 'Error: Error creating \'dm_rooms\': Error: SQLITE_ERROR: table dm_rooms already exists\n    at db.runAsync.then.catch (/root/.matrix-appservice-discord/build/src/store.js:96:19)\n    at tryCatcher (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/root/.matrix-appservice-discord/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)' }
ERR! discordas Error: Failure to update to latest schema.
ERR! discordas     at Error (native)
ERR! discordas     at DiscordStore.<anonymous> (/root/.matrix-appservice-discord/build/src/store.js:81:27)
ERR! discordas     at next (native)
ERR! discordas     at fulfilled (/root/.matrix-appservice-discord/build/src/store.js:4:58)
ERR! discordas  { Error: Failure to update to latest schema.
ERR! discordas     at Error (native)
ERR! discordas     at DiscordStore.<anonymous> (/root/.matrix-appservice-discord/build/src/store.js:81:27)
ERR! discordas     at next (native)
ERR! discordas     at fulfilled (/root/.matrix-appservice-discord/build/src/store.js:4:58)
ERR! discordas   stack: 'Error: Failure to update to latest schema.\n    at Error (native)\n    at DiscordStore.<anonymous> (/root/.matrix-appservice-discord/build/src/store.js:81:27)\n    at next (native)\n    at fulfilled (/root/.matrix-appservice-discord/build/src/store.js:4:58)' }
ERR! discordas Failure during startup. Exiting.

npm ERR! Linux 4.9.7-x86_64-linode80
npm ERR! argv "/root/.nvm/versions/node/v6.11.1/bin/node" "/root/.nvm/versions/node/v6.11.1/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! matrix-appservice-discord@0.0.1 start: `npm run-script build && node ./build/src/discordas.js -p 9005 -c config.yaml`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the matrix-appservice-discord@0.0.1 start script 'npm run-script build && node ./build/src/discordas.js -p 9005 -c config.yaml'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the matrix-appservice-discord package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run-script build && node ./build/src/discordas.js -p 9005 -c config.yaml
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs matrix-appservice-discord
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls matrix-appservice-discord
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     /root/.matrix-appservice-discord/npm-debug.log
root@ubuntu:~/.matrix-appservice-discord#
```

**Comment by Half-Shot** [comment]
I'm told this is fixed by #34, so we can close this. Reopen if the issues persists.
