### ISSUE TITLE
Sending messages from Matrix to Discord doesn't work.

### ISSUE THREAD

**Issue by Admicos** [Half-Shot/matrix-appservice-discord#235]
Here's the error I got:
```
21 Aug 21:08:54.110 [DiscordAS] verbose: matrix-appservice-bridge [-] GET http://synapse:8008/_matrix/client/r0/rooms/-- (AS) HTTP 200 "{\"membership\": \"join\", \"avatar_url\": \"mxc://matrix.issizler.club/---
21 Aug 21:08:54.392 [DiscordBot] error: Couldn't send message.  { DiscordAPIError: Invalid Form Body
avatar_url: Not a well formed URL.
    at item.request.gen.end (/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'DiscordAPIError',
  message: 'Invalid Form Body\navatar_url: Not a well formed URL.',
  path:
   '/api/v7/webhooks/-------?wait=true',
  code: 50035 }
21 Aug 21:08:54.397 [DiscordBot] verbose: Sent  null
21 Aug 21:08:54.397 [MatrixRoomHandler] warn: There was an error sending a matrix event TypeError: Cannot read property 'id' of null
    at msg.forEach (/build/src/bot.js:243:42)
    at Array.forEach (<anonymous>)
    at DiscordBot.<anonymous> (/build/src/bot.js:241:17)
    at Generator.throw (<anonymous>)
    at rejected (/build/src/bot.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This probably is something in my setup as there was a lot of experimentation going on while installing both Synapse and this service. (I'm new to Matrix)

**Comment by Admicos** [comment]
Welp, I fixed it.

I changed the homeserver URL in the config has to my public URL, and now it works.
