### ISSUE TITLE
Stuff fails if there is an empty userstore entry

### ISSUE THREAD

**Issue by Sorunome** [Half-Shot/matrix-appservice-discord#254]
Randomly (currently unknown cause) there is a new userstore entry for an already existing user, which is empty, which will cause stuff to fail down the road

```
Unhandled rejection TypeError: Cannot read property 'id' of null
    at UserSyncroniser.<anonymous> (/build/src/usersyncroniser.js:194:31)
    at Generator.next (<anonymous>)
    at /build/src/usersyncroniser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/build/src/usersyncroniser.js:3:12)
    at UserSyncroniser.GetUserStateForGuildMember (/build/src/usersyncroniser.js:192:16)
    at UserSyncroniser.<anonymous> (/build/src/usersyncroniser.js:106:38)
    at Generator.next (<anonymous>)
    at /build/src/usersyncroniser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/build/src/usersyncroniser.js:3:12)
    at UserSyncroniser.EnsureJoin (/build/src/usersyncroniser.js:105:16)
    at trySend.then.catch (/build/src/bot.js:537:54)
    at tryCatcher (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```
(thanks to traceback @turt2live)

**Comment by Sorunome** [comment]
This should be fixed with #394
