### ISSUE TITLE
"Event not processed by bridge" spam

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#298]
This happens fairly constantly:

```
Nov-13 20:44:55.475 [DiscordAS] verbose: matrix-appservice-bridge [biy0oqrzdr400] FAILED (19902ms) Error: Event not processed by bridge
    at MatrixRoomHandler.<anonymous> (/build/src/matrixroomhandler.js:161:19)
    at Generator.next (<anonymous>)
    at /build/src/matrixroomhandler.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/build/src/matrixroomhandler.js:3:12)
    at MatrixRoomHandler.OnEvent (/build/src/matrixroomhandler.js:101:16)
    at Object.onEvent (/build/src/discordas.js:77:97)
    at Bridge._onConsume (/node_modules/matrix-appservice-bridge/lib/bridge.js:781:30)
    at /node_modules/matrix-appservice-bridge/lib/bridge.js:980:14
    at tryCatcher (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate (timers.js:632:19)
```

**Comment by Half-Shot** [comment]
Yes, this should really be under verbose with just the eventID (and perhaps type,sender)

**Comment by Sorunome** [comment]
fixed
