### ISSUE TITLE
Cannot read property 'user' of null

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#360]
```
Dec-28 05:54:01.449 [DiscordBot] verbose: Failed to send message into room. TypeError: Cannot read property 'user' of null
    at UserSyncroniser.<anonymous> (/build/src/usersyncroniser.js:203:32)
    at Generator.next (<anonymous>)
    at /build/src/usersyncroniser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/build/src/usersyncroniser.js:3:12)
    at UserSyncroniser.GetUserStateForGuildMember (/build/src/usersyncroniser.js:201:16)
    at UserSyncroniser.<anonymous> (/build/src/usersyncroniser.js:104:38)
    at Generator.next (<anonymous>)
    at /build/src/usersyncroniser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/build/src/usersyncroniser.js:3:12)
    at UserSyncroniser.JoinRoom (/build/src/usersyncroniser.js:103:16)
    at DiscordBot.<anonymous> (/build/src/bot.js:699:45)
    at Generator.throw (<anonymous>)
    at rejected (/build/src/bot.js:5:65)
```

**Comment by Sorunome** [comment]
can you fetch this part of your compiled js file? `    at UserSyncroniser.<anonymous> (/build/src/usersyncroniser.js:203:32)` so that we can tell where in typescript that is. Thanks!

**Comment by turt2live** [comment]
```
    GetUserStateForGuildMember(newMember) {
        return __awaiter(this, void 0, void 0, function* () {
            const guildState = Object.assign({}, DEFAULT_GUILD_STATE, {
                bot: newMember.user.bot,                                  // <<--- Line 203
                displayColor: newMember.displayColor,
                displayName: newMember.displayName,
                id: newMember.id,
```

**Comment by Sorunome** [comment]
to verify a possible reason for this, can you also fetch this one? `    at DiscordBot.<anonymous> (/build/src/bot.js:699:45)`

**Comment by turt2live** [comment]
```
                    const afterSend = (re) => __awaiter(this, void 0, void 0, function* () {
                        const evt = new dbdataevent_1.DbEvent();
                        evt.MatrixId = `${re.event_id};${room}`;
                        evt.DiscordId = msg.id;
                        evt.ChannelId = msg.channel.id;
                        evt.GuildId = msg.guild.id;
                        yield this.store.Insert(evt);
                    });
                    let res;
                    try {
                        res = yield trySend();
                        yield afterSend(res);
                    }
                    catch (e) {                                                 // <<--- Line 699
                        if (e.errcode !== "M_FORBIDDEN") {
                            log.error("DiscordBot", "Failed to send message into room.", e);
                            return;
                        }
                        yield this.userSync.JoinRoom(msg.member, room);
                        res = yield trySend();
                        yield afterSend(res);
                    }
                }));

```

**Comment by Half-Shot** [comment]
This inspired #367 :)

**Comment by Sorunome** [comment]
Got fixed
