### ISSUE TITLE
Discord->Matrix messages dropped on latest develop

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#393]
Only possible error is
```
Feb-6 05:46:56.681 [DiscordBot] error: Caught while handing 'message' TypeError: Cannot read property 'getRemoteUser' of undefined
    at UserSyncroniser.<anonymous> (/src/usersyncroniser.ts:238:49)
    at Generator.next (<anonymous>)
    at /build/src/usersyncroniser.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/build/src/usersyncroniser.js:18:12)
    at UserSyncroniser.GetUserUpdateState (/build/src/usersyncroniser.js:188:16)
    at UserSyncroniser.<anonymous> (/src/usersyncroniser.ts:101:38)
    at Generator.next (<anonymous>)
    at /build/src/usersyncroniser.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/build/src/usersyncroniser.js:18:12)
    at UserSyncroniser.OnUpdateUser (/build/src/usersyncroniser.js:66:16)
    at DiscordBot.<anonymous> (/src/bot.ts:776:29)
    at Generator.next (<anonymous>)
    at /build/src/bot.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/build/src/bot.js:18:12)
    at DiscordBot.OnMessage (/build/src/bot.js:683:16)
    at DiscordBot.<anonymous> (/src/bot.ts:225:36)
    at Generator.next (<anonymous>)
    at fulfilled (/build/src/bot.js:19:58)
```

**Comment by Half-Shot** [comment]
Fixed in a6f8330f3f3492beb68d88b31c7d98a387d90448
