### ISSUE TITLE
'types/chai-as-promised' is not in the npm registry.

### ISSUE THREAD

**Issue by tchncs** [Half-Shot/matrix-appservice-discord#4]
Hi there, looks like we have a tiny problem :)

```
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/chai-as-promised' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'matrix-appservice-discord'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.11-1-ARCH
npm ERR! command "/home/user/.nvm/v0.10.32/bin/node" "/home/technics/.nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /home/user/app/matrix-appservice-discord
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/app/matrix-appservice-discord/npm-debug.log
npm ERR! not ok code 0
```

**Comment by tchncs** [comment]
I just installed them by hand and ended up in

```
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/home/user/.nvm/v0.10.32/lib/node_modules/npm/lib/cache/add-named.js:219:35)
npm ERR!     at /home/user/.nvm/v0.10.32/lib/node_modules/npm/lib/cache/add-named.js:207:5
npm ERR!     at RegClient.get_ (/home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:130:14)
npm ERR!     at RegClient.<anonymous> (/home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:49:12)
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.11-1-ARCH
npm ERR! command "/home/user/.nvm/v0.10.32/bin/node" "/home/user/.nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /home/user/app/matrix-appservice-discord
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! type non_object_property_load
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/home/user/.nvm/v0.10.32/lib/node_modules/npm/lib/cache/add-named.js:219:35)
npm ERR!     at /home/user/.nvm/v0.10.32/lib/node_modules/npm/lib/cache/add-named.js:207:5
npm ERR!     at RegClient.get_ (/home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:130:14)
npm ERR!     at RegClient.<anonymous> (/home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:49:12)
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.11-1-ARCH
npm ERR! command "/home/user/.nvm/v0.10.32/bin/node" "/home/user/.nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /home/user/app/matrix-appservice-discord
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! type non_object_property_load
npm ERR! TypeError: Cannot read property '0.0.29' of undefined
npm ERR!     at /home/user/.nvm/v0.10.32/lib/node_modules/npm/lib/cache/add-named.js:123:27
npm ERR!     at RegClient.get_ (/home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:130:14)
npm ERR!     at RegClient.<anonymous> (/home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:49:12)
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.11-1-ARCH
npm ERR! command "/home/user/.nvm/v0.10.32/bin/node" "/home/user/.nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /home/user/app/matrix-appservice-discord
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! type non_object_property_load
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/home/user/.nvm/v0.10.32/lib/node_modules/npm/lib/cache/add-named.js:219:35)
npm ERR!     at /home/user/.nvm/v0.10.32/lib/node_modules/npm/lib/cache/add-named.js:207:5
npm ERR!     at RegClient.get_ (/home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:130:14)
npm ERR!     at RegClient.<anonymous> (/home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:49:12)
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /home/user/.nvm/v0.10.32/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.11-1-ARCH
npm ERR! command "/home/user/.nvm/v0.10.32/bin/node" "/home/user/.nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /home/user/app/matrix-appservice-discord
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/app/matrix-appservice-discord/npm-debug.log
npm ERR! not ok code 0
```

**Comment by tchncs** [comment]
Uh i am not sure but i guess i was just missing a npm install -g npm o.O
`/build/discordas.js` is still missing.
