### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by RhythmLunatic** [Half-Shot/matrix-appservice-discord#416]
Cloned develop branch and ran npm install and npm run build.
```
> matrix-appservice-discord@0.4.0 build /root/matrix-appservice-discord
> tsc

error TS2688: Cannot find type definition file for 'mocha'.

error TS2688: Cannot find type definition file for 'node'.


Found 2 errors.


npm ERR! Linux 2.6.32-042stab133.2
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v11.12.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! matrix-appservice-discord@0.4.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the matrix-appservice-discord@0.4.0 build script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the matrix-appservice-discord package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs matrix-appservice-discord
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls matrix-appservice-discord
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2019-03-18T16_49_18_150Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@4.2.0
3 info using node@v11.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle matrix-appservice-discord@0.4.0~prebuild: matrix-appservice-discord@0.4.0
6 silly lifecycle matrix-appservice-discord@0.4.0~prebuild: no script for prebuild, continuing
7 info lifecycle matrix-appservice-discord@0.4.0~build: matrix-appservice-discord@0.4.0
8 verbose lifecycle matrix-appservice-discord@0.4.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle matrix-appservice-discord@0.4.0~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/matrix-appservice-discord/node_modules/.bin:/root/.pyenv/plugins/pyenv-virtualenv/shims:/root/.pyenv/shims:/root/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle matrix-appservice-discord@0.4.0~build: CWD: /root/matrix-appservice-discord
11 silly lifecycle matrix-appservice-discord@0.4.0~build: Args: [ '-c', 'tsc' ]
12 silly lifecycle matrix-appservice-discord@0.4.0~build: Returned: code: 2  signal: null
13 info lifecycle matrix-appservice-discord@0.4.0~build: Failed to exec build script
14 verbose stack Error: matrix-appservice-discord@0.4.0 build: `tsc`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at EventEmitter.emit (events.js:197:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at ChildProcess.emit (events.js:197:13)
14 verbose stack     at maybeClose (internal/child_process.js:988:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
15 verbose pkgid matrix-appservice-discord@0.4.0
16 verbose cwd /root/matrix-appservice-discord
17 error Linux 2.6.32-042stab133.2
18 error argv "/usr/local/bin/node" "/usr/bin/npm" "run" "build"
19 error node v11.12.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error matrix-appservice-discord@0.4.0 build: `tsc`
23 error Exit status 2
24 error Failed at the matrix-appservice-discord@0.4.0 build script 'tsc'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the matrix-appservice-discord package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     tsc
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs matrix-appservice-discord
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls matrix-appservice-discord
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

**Comment by Sorunome** [comment]
what's the output of `npm --version` and `node --version`?

**Comment by turt2live** [comment]
> 2 info using npm@4.2.0
> 3 info using node@v11.12.0

From the logs btw - my bet is outdated npm

**Comment by Half-Shot** [comment]
I believe this isn't still the case.
