### ISSUE TITLE
`plumbed` column is not correctly cast when inserting/updating

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#421]
```
Mar-27 18:49:23.624 [MatrixRoomHandler] info: Got request for # _discord_REDACTED_REDACTED
Mar-27 18:49:23.624 [MatrixRoomHandler] info: Creating # _discord_REDACTED_REDACTED
Mar-27 18:49:24.127 [DiscordAS] error: Exception thrown while handling "onAliasQuery" event { error: column "plumbed" is of type boolean but expression is of type integer
    at Connection.parseE (/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
  name: 'error',
  length: 189,
  severity: 'ERROR',
  code: '42804',
  detail: undefined,
  hint: 'You will need to rewrite or cast the expression.',
  position: '365',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '540',
  routine: 'transformAssignedExpr' }
```

**Comment by Sorunome** [comment]
which branch is this on?

Am 28. März 2019 07:51:11 GMT+13:00 schrieb Travis Ralston <notifications@github.com>:

**Comment by turt2live** [comment]
https://github.com/t2bot/matrix-appservice-discord

**Comment by Sorunome** [comment]
fixed
