### ISSUE TITLE
Unable to create discord-registration.yaml

### ISSUE THREAD

**Issue by Ryonez** [Half-Shot/matrix-appservice-discord#427]
I'm unable to discord-registration.yaml, node is throwing an error on the very first command.

```
ryonez@GALACTICA C:\Programming\Node\matrix-appservice-discord
$ npm install

> integer@2.1.0 install C:\Programming\Node\matrix-appservice-discord\node_modules\integer
> node-gyp rebuild


ryonez@GALACTICA C:\Programming\Node\matrix-appservice-discord\node_modules\integer
$ if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\ryonez\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Programming\Node\matrix-appservice-discord\node_modules\integer
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ryonez\AppData\Roaming\npm-cache\_logs\2019-04-14T01_00_46_588Z-debug.log

ryonez@GALACTICA C:\Programming\Node\matrix-appservice-discord
```

Please provide an example file. I'm using docker and I just want to get this over with now.

**Comment by Ryonez** [comment]
This is nuts. Just installed the latest node.js instead of LTS, and now it wants me to download 4.6GB for the VC++ 2015.3 v14.00 (v140) toolset for desktop...

I'm not doing that for a tiny file that can be edited by hand.

**Comment by Ryonez** [comment]
I ended up ignoring errors and such and got a file to use.

After a little editing got it going.
