### ISSUE TITLE
Files with undetermined MIME type are not forwarded from Matrix to Discord

### ISSUE THREAD

**Issue by pacien** [Half-Shot/matrix-appservice-discord#500]
Files with undetermined MIME type (`dd if=/dev/zero of=test_file bs=7M count=1`) are not relayed from Matrix to Discord.

Perhaps should the bridge fallback to some generic value when it's not able to guess the MIME type.

Log snippet:
```
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]: Jun-16 15:40:13.484 [MatrixEventProcessor] warn: There was an error sending a matrix event TypeError: Cannot read property 'match' of undefined
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at Mime.extension (/nix/store/jljsvhk13ckz4rqfs7rnkbfvs0pxc4dr-node_matrix-appservice-discord-0.5.1/lib/node_modules/matrix-appservice-discord/node_modules/mime/mime.js:79:23)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at MatrixEventProcessor.GetFilenameForMediaEvent (/nix/store/jljsvhk13ckz4rqfs7rnkbfvs0pxc4dr-node_matrix-appservice-discord-0.5.1/lib/node_modules/matrix-appservice-discord/src/matrixeventprocessor.ts:493:59)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at MatrixEventProcessor.<anonymous> (/nix/store/jljsvhk13ckz4rqfs7rnkbfvs0pxc4dr-node_matrix-appservice-discord-0.5.1/lib/node_modules/matrix-appservice-discord/src/matrixeventprocessor.ts:309:27)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at Generator.next (<anonymous>)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at /nix/store/jljsvhk13ckz4rqfs7rnkbfvs0pxc4dr-node_matrix-appservice-discord-0.5.1/lib/node_modules/matrix-appservice-discord/build/src/matrixeventprocessor.js:22:71
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at new Promise (<anonymous>)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at __awaiter (/nix/store/jljsvhk13ckz4rqfs7rnkbfvs0pxc4dr-node_matrix-appservice-discord-0.5.1/lib/node_modules/matrix-appservice-discord/build/src/matrixeventprocessor.js:18:12)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at MatrixEventProcessor.HandleAttachment (/nix/store/jljsvhk13ckz4rqfs7rnkbfvs0pxc4dr-node_matrix-appservice-discord-0.5.1/lib/node_modules/matrix-appservice-discord/build/src/matrixeventprocessor.js:272:16)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at MatrixEventProcessor.<anonymous> (/nix/store/jljsvhk13ckz4rqfs7rnkbfvs0pxc4dr-node_matrix-appservice-discord-0.5.1/lib/node_modules/matrix-appservice-discord/src/matrixeventprocessor.ts:173:33)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at Generator.next (<anonymous>)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at fulfilled (/nix/store/jljsvhk13ckz4rqfs7rnkbfvs0pxc4dr-node_matrix-appservice-discord-0.5.1/lib/node_modules/matrix-appservice-discord/build/src/matrixeventprocessor.js:19:58)
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at <anonymous>
Jun 16 15:40:13 matrix matrix-appservice-discord[7986]:     at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by Sorunome** [comment]
fixed in #501
