### ISSUE TITLE
TypeError: guild.members.has is not a function

### ISSUE THREAD

**Issue by pacien** [Half-Shot/matrix-appservice-discord#628]
```
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]: Nov-6 22:33:19.219 [UserSync] error: Failed to update user's profile TypeError: guild.members.has is not a function
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at UserSyncroniser.<anonymous> (/nix/store/g3wyhvahbxyda3kfnlp8rl1zrri39p74-matrix-appservice-discord-1.0.0-rc3/libexec/matrix-appservice-discord/deps/matrix-appservice-discord/src/usersyncroniser.ts:403:31)
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at Generator.next (<anonymous>)
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at /nix/store/g3wyhvahbxyda3kfnlp8rl1zrri39p74-matrix-appservice-discord-1.0.0-rc3/libexec/matrix-appservice-discord/deps/matrix-appservice-discord/build/src/usersyncroniser.js:23:71
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at new Promise (<anonymous>)
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at __awaiter (/nix/store/g3wyhvahbxyda3kfnlp8rl1zrri39p74-matrix-appservice-discord-1.0.0-rc3/libexec/matrix-appservice-discord/deps/matrix-appservice-discord/build/src/usersyncroniser.js:19:12)
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at /nix/store/g3wyhvahbxyda3kfnlp8rl1zrri39p74-matrix-appservice-discord-1.0.0-rc3/libexec/matrix-appservice-discord/deps/matrix-appservice-discord/src/usersyncroniser.ts:402:75
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at Function.<anonymous> (/nix/store/g3wyhvahbxyda3kfnlp8rl1zrri39p74-matrix-appservice-discord-1.0.0-rc3/libexec/matrix-appservice-discord/deps/matrix-appservice-discord/src/util.ts:301:19)
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at Generator.next (<anonymous>)
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at /nix/store/g3wyhvahbxyda3kfnlp8rl1zrri39p74-matrix-appservice-discord-1.0.0-rc3/libexec/matrix-appservice-discord/deps/matrix-appservice-discord/build/src/util.js:23:71
Nov 06 22:33:19 hp2 matrix-appservice-discord[3992]:     at new Promise (<anonymous>)
```

On v1.0.0-rc3.

**Comment by pacien** [comment]
Fixed by 6dfed195d9a669b2ee948ffcdbbc08202124f40c in #627.
