### ISSUE TITLE
Cannot send messages: avatar_url: Not a well formed URL

### ISSUE THREAD

**Issue by spantaleev** [Half-Shot/matrix-appservice-discord#649]
Trying to send a message, I'm getting this every time:

```
[bot-sdkAppservice] info: [ 'Processing transaction 6474' ]
[bot-sdkAppservice] info: [ 'Processing event of type m.room.message' ]
[MatrixEventProcessor] verbose: Got m.room.message event
[MatrixEventProcessor] verbose: Looking up XXXXXXX_XXXXX
[MatrixEventProcessor] verbose: Profile @user:example.com:!ZZynfOEfEfrCnuHjp:example.com not cached
[bot-sdkMatrixLiteClient (REQ-1)] info: [
'GET http://matrix-synapse:8008/_matrix/client/r0/rooms/!ZZynfOEfEfrCnuHjp%3Aexample.com/state/m.room.member/%40user%3Aexample.com'
]
172.18.0.4 - - [16/Dec/2020:00:50:51 +0000] "PUT /transactions/6474?access_token=TOKEN_HERE HTTP/1.1" 200 2 "-" "Synapse/1.24.0"

[DiscordBot] warn: Failed to send message $BBBB9npTjGKft-bj8vpYsfdo09FNwbNIjRGhFEVCEcXqZk

[DiscordBot] verbose: DiscordAPIError: Invalid Form Body
avatar_url: Not a well formed URL.
at RequestHandler.execute (/node_modules/better-discord.js/src/rest/RequestHandler.js:170:25)
at processTicksAndRejections (internal/process/task_queues.js:93:5) {
method: 'post',
path: '/webhooks/XXXXX/AAAAAA-BBBBBB?wait=true',
code: 50035,
httpStatus: 400
}

[bot-sdkMatrixLiteClient (REQ-2)] info: [
'POST http://matrix-synapse:8008/_matrix/client/r0/rooms/!ZZynfOEfEfrCnuHjp%3Aexample.com/receipt/m.read/%2AAAA-BBBB'
]
```

It last worked some 3 days ago, and now that I try it, it doesn't work anymore. At first, I thought I broke it during the SQLite -> Postgres migration I've been working on for spantaleev/matrix-docker-ansible-deploy#740, but I've tried with my old SQLite database and it's still the same.

I'm using `docker.io/halfshot/matrix-appservice-discord:v1.0.0`.

**Comment by spantaleev** [comment]
Receiving messages still works. It's just sending that seems to be broken.

**Comment by auscompgeek** [comment]
~~Huh, Synapse validates avatar_url in member events now?~~

**Comment by spantaleev** [comment]
This seems to be caused by https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/748

**Comment by spantaleev** [comment]
I believe this should be fixed now (by using a public URL in `bridge.homeserverUrl` instead of a local one), but I'll confirm it tomorrow.

**Comment by spantaleev** [comment]
The problem is indeed resolved. Thanks @auscompgeek for helping me troubleshoot it!
