### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0 on npm start

### ISSUE THREAD

**Issue by krishnerkar** [Half-Shot/matrix-appservice-discord#668]
On running `npm start`,  I'm getting the following errors. 

This is the complete log file of the error.

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle matrix-appservice-discord@1.0.0~prestart: matrix-appservice-discord@1.0.0
6 info lifecycle matrix-appservice-discord@1.0.0~start: matrix-appservice-discord@1.0.0
7 verbose lifecycle matrix-appservice-discord@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle matrix-appservice-discord@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/krishnerkar/Downloads/matrix-appservice-discord-develop/node_modules/.bin:/home/krishnerkar/anaconda3/condabin:/home/krishnerkar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle matrix-appservice-discord@1.0.0~start: CWD: /home/krishnerkar/Downloads/matrix-appservice-discord-develop
10 silly lifecycle matrix-appservice-discord@1.0.0~start: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npm run-script build && node ./build/src/discordas.js -c config.yaml'
10 silly lifecycle ]
11 silly lifecycle matrix-appservice-discord@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle matrix-appservice-discord@1.0.0~start: Failed to exec start script
13 verbose stack Error: matrix-appservice-discord@1.0.0 start: `npm run-script build && node ./build/src/discordas.js -c config.yaml`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid matrix-appservice-discord@1.0.0
15 verbose cwd /home/krishnerkar/Downloads/matrix-appservice-discord-develop
16 verbose Linux 5.8.0-7630-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.18.2
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error matrix-appservice-discord@1.0.0 start: `npm run-script build && node ./build/src/discordas.js -c config.yaml`
22 error Exit status 1
23 error Failed at the matrix-appservice-discord@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by Sorunome** [comment]
sounds like your homserverUrl in the config.yaml is set wrong

**Comment by krishnerkar** [comment]
> sounds like your homserverUrl in the config.yaml is set wrong

Cool Thanks, its working now, i'm facing another issue now, will raise a new issue for it
