### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE on user registration after startup

### ISSUE THREAD

**Issue by OdinGitDat** [Half-Shot/matrix-appservice-discord#711]
I ran `ansible-playbook -i inventory/hosts setup.yml --tags=start -kK` for the first time and the discord appservice errored out. Journalctl showed this:

```
Jun 04 01:43:35 ubuntumatrix systemd[1]: Starting Matrix Appservice Discord bridge...
Jun 04 01:43:40 ubuntumatrix systemd[1]: Started Matrix Appservice Discord bridge.
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]: Jun-4 01:43:42.721 [bot-sdkMatrixLiteClient (REQ-1)] error: [
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:   Error: unable to verify the first certificate
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:       at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:       at TLSSocket.emit (events.js:315:20)
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:       at TLSSocket._finishInit (_tls_wrap.js:932:8)
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:     code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:   }
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]: ]
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]: Jun-4 01:43:42.722 [bot-sdkAppservice] error: [ 'Encountered error registering user: ' ]
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]: Jun-4 01:43:42.722 [bot-sdkAppservice] error: [
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:   Error: unable to verify the first certificate
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:       at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:       at TLSSocket.emit (events.js:315:20)
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:       at TLSSocket._finishInit (_tls_wrap.js:932:8)
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:     code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:   }
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]: ]
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]: Jun-4 01:43:42.724 [DiscordAS] error: A fatal error occurred during startup: Error: unable to verify the first certificate
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:     at TLSSocket.emit (events.js:315:20)
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:     at TLSSocket._finishInit (_tls_wrap.js:932:8)
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]:   code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
Jun 04 01:43:42 ubuntumatrix matrix-appservice-discord[20264]: }
Jun 04 01:43:43 ubuntumatrix systemd[1]: matrix-appservice-discord.service: Main process exited, code=exited, status=1/FAILURE
Jun 04 01:43:43 ubuntumatrix systemd[1]: matrix-appservice-discord.service: Failed with result 'exit-code'.
```

**Comment by jaller94** [comment]
I guess your computer wasn't properly connected to the Internet or a webserver's HTTPS certificate (likely the Matrix homeserver) was configured improperly.
