### ISSUE TITLE
one way transmission ( Only Discord ->Matrix)

### ISSUE THREAD

**Issue by V1TA5** [Half-Shot/matrix-appservice-discord#712]
Hi,
one of my bridged Channels suddenly only transmits messages form Discord to Matrix and not the other way around.
Other channels (even on the same Discord "Server") still work both ways.

I tried:
Restarting the Bridge
Rebooting the machiene the bridge runs on
Reboot Server Matrix server is running on
"Rebridge" the channel

Suggestions?

**Comment by neutralinsomniac** [comment]
I'm in the same boat. The only messages I get from the log are of the form:
`Jun-8 20:41:07.400 [DiscordBot] warn: Failed to send message $UbHNhS-QsjLujC4_8-SohbKbce4p2d-kTu2I3NNWsGc`

**Comment by henesy** [comment]
+1 matrix -> discord failing

**Comment by showermat** [comment]
I'm sure there are multiple reasons this might happen, but in my particular case it was because Ubuntu's default version of NodeJS is old (currently 10).  #630 got me on the right track and upgrading to version 16 fixed it.

**Comment by 2ro** [comment]
> I'm sure there are multiple reasons this might happen, but in my particular case it was because Ubuntu's default version of NodeJS is old (currently 10). #630 got me on the right track and upgrading to version 16 fixed it.

I think there are multiple reasons why this would happen as upgrading to nodejs v 16 did not work for me.

**Comment by jesterpm** [comment]
Has anyone found a resolution besides upgrading NodeJS? I'm running the latest version in Docker, but I'm still seeing one-way messages.

I see "Failed to send message" in the logs, along with a Method Not Allowed error response from the Discord API. Discord.js users reported a similar issue as this (https://github.com/discordjs/discord.js/issues/5731), but it was apparently a regression on the Discord API.

**Comment by Gigadoc2** [comment]
This might be completely unrelated, but did you check whether the webhooks in the Discord Guild all belong to the bot user of your bridge?

I encountered a very similar sounding problem, but in a specific situation: I first used the t2bot.io bridge for a certain Guild, then switched to self-hosting the appservice (due to t2bot.io being heavily rate-limited by Discord). On that switch, the old bot was removed from the Guild, but _not_ the webhooks it had set up. This was no problem at first, the bridge could for some reason re-use the webhooks set down by t2bot.io. My guess is, Discord fixed this some time back, when the problems started. At least for me the timing seems right. It was solved by removing the t2bot "Integration" on the Discord side, then the appservice will recreate the webhooks on its own.

**Comment by pini-gh** [comment]
I've been experiencing this very same issue since a few weeks. The log says:
```
Jul-25 15:14:42.168 [DiscordBot] warn: Failed to send message $2AXGkcJKjPnIeu58YUY3l2hmJ093ncLy6In_qm3ZWuk
Jul-25 15:14:42.171 [DiscordBot] verbose: DiscordAPIError: 405: Method Not Allowed
    at RequestHandler.execute (/node_modules/better-discord.js/src/rest/RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
```
I run an up to date self hosted Docker instance using `halfshot/matrix-appservice-discord:latest`.

@Gigadoc2 The context you describe is similar to mine. But the previous bot was set up by another user. Would you mind describing what you mean with:
> removing the t2bot "Integration" on the Discord side

?

**Comment by pini-gh** [comment]
I had this old bot removed from discord by its owner and messages are handled both ways again. Yay! Thanks @Gigadoc2 for the hint!

**Comment by V1TA5** [comment]
I reinstalled the whole Machine 3x. I never solved the original one way problem but found out that i need to use the releases and not the master repo so it would compile.

**Comment by jesterpm** [comment]
I finally got my issue worked out by deleting the _matrix webhook from the Discord server. As soon as it was deleted, the bot recreated the webhook and everything worked perfectly.
