### ISSUE TITLE
Error when using Docker container: 'User ID already taken'

### ISSUE THREAD

**Issue by hwittenborn** [Half-Shot/matrix-appservice-discord#721]
I'm seeing this error, which appears to be causing everything to not work properly:

```
[bot-sdkMatrixLiteClient (REQ-1)] error: [ { errcode: 'M_USER_IN_USE', error: 'User ID already taken.' } ]
```

After this the container appears to just be quitting, and the bot doesn't do anything like join rooms.

**Comment by d-513** [comment]
same error

**Comment by Sorunome** [comment]
Those should be safe to ignore. What are your "not working" symptoms?

**Comment by hwittenborn** [comment]
"Not working" is the following:

- The bot isn't joining
- The bot appeared to quit after the message in the first post showed up

I'm not sure why, but attempting to run `docker logs` on the container is also mysteriously not showing anything now.

**Comment by hwittenborn** [comment]
Just turned on `verbose` logging, and it's outputting logs just fine again.

It's also saying that the bot started successfully now (don't know why the error's just gone now; I did change over to the `develop` image beforehand though), but the issue about the bot not joining rooms is still present.

**Comment by hwittenborn** [comment]
Went back to the `latest` image, but I'm still not getting any dice with it joining rooms (the original error's still gone though, so it's a step in the right direction anyway).

**Comment by Synkstar** [comment]
Im getting this same issue actually. Its just the bot doesnt join the matrix room when its invited but it shows up on discord as being online.

`discordrelay_1  | Dec-7 13:15:54.636 [bot-sdkMatrixLiteClient (REQ-1)] error: [ { errcode: 'M_USER_IN_USE', error: 'User ID already taken.' } ]
discordrelay_1  | PayloadTooLargeError: request entity too large
discordrelay_1  |     at readStream (/node_modules/raw-body/index.js:155:17)
discordrelay_1  |     at getRawBody (/node_modules/raw-body/index.js:108:12)
discordrelay_1  |     at read (/node_modules/body-parser/lib/read.js:77:3)
discordrelay_1  |     at jsonParser (/node_modules/body-parser/lib/types/json.js:135:5)
discordrelay_1  |     at Layer.handle [as handle_request] (/node_modules/matrix-bot-sdk/node_modules/express/lib/router/layer.js:95:5)
discordrelay_1  |     at trim_prefix (/node_modules/matrix-bot-sdk/node_modules/express/lib/router/index.js:317:13)
discordrelay_1  |     at /node_modules/matrix-bot-sdk/node_modules/express/lib/router/index.js:284:7
discordrelay_1  |     at Function.process_params (/node_modules/matrix-bot-sdk/node_modules/express/lib/router/index.js:335:12)
discordrelay_1  |     at next (/node_modules/matrix-bot-sdk/node_modules/express/lib/router/index.js:275:10)
discordrelay_1  |     at expressInit (/node_modules/matrix-bot-sdk/node_modules/express/lib/middleware/init.js:40:5)
discordrelay_1  | PayloadTooLargeError: request entity too large`

**Comment by Synkstar** [comment]
I just fixed it. I had matrix.nasulex.net as the domain and thats what was causing the problem. The domain is supposed to be what it displays as so I had to put mine to nasulex.net because its delegated to that. But you still have to leave the homeserverurl as the direct link to the server which is matrix.nasulex.net in my case

**Comment by hwittenborn** [comment]
I wouldn't be able to confirm on my end if the issue still persists, as I've since stopped using Discord for the purposes I was using the bridge for and I can't really confirm if anything fixes it anymore.

I'll leave it up to y'all to decide what to do with this issue.

**Comment by rjohnson91** [comment]
I'm experiencing the same error. Bot won't join matrix server.

**Comment by laur89** [comment]
> Those should be safe to ignore. What are your "not working" symptoms?

Should it be logged as `error` then?

**Comment by Wamy-Dev** [comment]
any fix?
