### ISSUE TITLE
discord-registration.yaml not generated

### ISSUE THREAD

**Issue by korefuji** [Half-Shot/matrix-appservice-discord#73]
`node build/src/discordas.js -r -u "http://localhost:9005" -c config/config.yaml
Loading config file /home/jinsan/matrix-appservice-discord/config/config.yaml
{"instanceContext":"#/auth/clientID","resolutionScope":"anon-schema://157704f2c9e746d639d93f87d1bcea0fa55626ad/#/properties/auth/properties/clientID","constraintName":"type","constraintValue":"string","testedValue":"integer"}
{"instanceContext":"#/auth/secret","resolutionScope":"anon-schema://157704f2c9e746d639d93f87d1bcea0fa55626ad/#/properties/auth/properties/secret","constraintName":"type","constraintValue":"string","testedValue":"null"}
{"instanceContext":"#/auth/botToken","resolutionScope":"anon-schema://157704f2c9e746d639d93f87d1bcea0fa55626ad/#/properties/auth/properties/botToken","constraintName":"type","constraintValue":"string","testedValue":"null"}
Init Failed to start bridge.
Init { Error: Failed to validate file
    at ConfigValidator.validate (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:45:17)
    at Cli._loadConfig (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:159:22)
    at Cli._assignConfigFile (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:144:23)
    at Cli.run (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:115:18)
    at Object.<anonymous> (/home/jinsan/matrix-appservice-discord/build/src/discordas.js:20:9)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
  _validationErrors: 
   [ { Error
    at Object.module.exports [as type] (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/keywords/type.js:22:19)
    at run (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/index.js:122:46)
    at module.exports (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/keywords/_propertiesImpl.js:44:30)
    at run (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/index.js:133:28)
    at module.exports (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/keywords/_propertiesImpl.js:44:30)
    at run (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/index.js:133:28)
    at JaySchema._validateImpl (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/jayschema.js:227:10)
    at JaySchema.validate (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/jayschema.js:294:29)
    at ConfigValidator.validate (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:33:21)
    at Cli._loadConfig (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:159:22)
    at Cli._assignConfigFile (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:144:23)
    at Cli.run (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:115:18)
    at Object.<anonymous> (/home/jinsan/matrix-appservice-discord/build/src/discordas.js:20:9)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
       instanceContext: '#/auth/clientID',
       resolutionScope: 'anon-schema://157704f2c9e746d639d93f87d1bcea0fa55626ad/#/properties/auth/properties/clientID',
       constraintName: 'type',
       constraintValue: 'string',
       testedValue: 'integer' },
     { Error
    at Object.module.exports [as type] (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/keywords/type.js:28:19)
    at run (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/index.js:122:46)
    at module.exports (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/keywords/_propertiesImpl.js:44:30)
    at run (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/index.js:133:28)
    at module.exports (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/keywords/_propertiesImpl.js:44:30)
    at run (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/index.js:133:28)
    at JaySchema._validateImpl (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/jayschema.js:227:10)
    at JaySchema.validate (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/jayschema.js:294:29)
    at ConfigValidator.validate (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:33:21)
    at Cli._loadConfig (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:159:22)
    at Cli._assignConfigFile (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:144:23)
    at Cli.run (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:115:18)
    at Object.<anonymous> (/home/jinsan/matrix-appservice-discord/build/src/discordas.js:20:9)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
       instanceContext: '#/auth/secret',
       resolutionScope: 'anon-schema://157704f2c9e746d639d93f87d1bcea0fa55626ad/#/properties/auth/properties/secret',
       constraintName: 'type',
       constraintValue: 'string',
       testedValue: 'null' },
     { Error
    at Object.module.exports [as type] (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/keywords/type.js:28:19)
    at run (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/index.js:122:46)
    at module.exports (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/keywords/_propertiesImpl.js:44:30)
    at run (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/index.js:133:28)
    at module.exports (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/keywords/_propertiesImpl.js:44:30)
    at run (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/suites/draft-04/index.js:133:28)
    at JaySchema._validateImpl (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/jayschema.js:227:10)
    at JaySchema.validate (/home/jinsan/matrix-appservice-discord/node_modules/jayschema/lib/jayschema.js:294:29)
    at ConfigValidator.validate (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:33:21)
    at Cli._loadConfig (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:159:22)
    at Cli._assignConfigFile (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:144:23)
    at Cli.run (/home/jinsan/matrix-appservice-discord/node_modules/matrix-appservice-bridge/lib/components/cli.js:115:18)
    at Object.<anonymous> (/home/jinsan/matrix-appservice-discord/build/src/discordas.js:20:9)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
       instanceContext: '#/auth/botToken',
       resolutionScope: 'anon-schema://157704f2c9e746d639d93f87d1bcea0fa55626ad/#/properties/auth/properties/botToken',
       constraintName: 'type',
       constraintValue: 'string',
       testedValue: 'null' } ] }
(node:9180) ExperimentalWarning: The http2 module is an experimental API.
`

Get the output there, when trying to generate the discord-registration,yaml. Either instructions arent clear, or I've done something wrong? For example, do I place the information for the bot BEFORE I run the build command, and where does the file output to, what is the name of the generated file? discord-registration.yaml?

**Comment by Half-Shot** [comment]
Oh hold up, you shouldn't need to configure anything before running build. For example, the tests on TravisCI run build with an empty config file. The validation should only be done when starting the bridge.
