### ISSUE TITLE
discord -> matrix no longer working, unclear error message

### ISSUE THREAD

**Issue by verymilan** [Half-Shot/matrix-appservice-discord#765]
hi, some days ago, the bridge stopped properly working for me. only messages to matrix still work. each processed/skipped event in my log attaches the following error which i don't know how to handle:

````
Dec-27 14:35:03.704 [bot-sdkAppservice] info: [ 'Processing transaction 21315994' ]
Dec-27 14:35:03.704 [bot-sdkAppservice] info: [ 'Processing event of type m.room.member' ]
Dec-27 14:35:03.704 [bot-sdkAppservice] error: [
  RangeError: Value undefined out of range for undefined options property undefined
      at Set.add (<anonymous>)
      at DiscordStore.setTransactionCompleted (matrix-appservice-discord/src/store.ts:293:21)
      at Appservice.<anonymous> (matrix-appservice-discord/node_modules/matrix-bot-sdk/lib/appservice/Appservice.js:447:52)
      at Generator.next (<anonymous>)
      at fulfilled (matrix-appservice-discord/node_modules/matrix-bot-sdk/lib/appservice/Appservice.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
]
````
i have tried updating to the latest develop commit, but nothing changed. 
 
i hope somebody can help me out here. sadly there was no response in the matrix room and i am not sure if this might be some sort of bug or not.

**Comment by NickUfer** [comment]
Seems to be a problem with a too big set / too many processed transactions / a too long running process. A quick glance at the source code shows that the too big Set is never cleared, thus filling up until a limit of 2^24 entries:

https://stackoverflow.com/questions/54452896/maximum-number-of-entries-in-node-js-map/54466812#54466812

This seems to be the fix: https://github.com/nodejs/node/issues/37320

Maybe I get around to create a PR to fix this this week

**Comment by NickUfer** [comment]
When the bridge starts all transaction ids are loaded into ram. Maybe it is possible to only keep the newest n txids to fix this bug and also reduce memory consumption significantly (around 800-850MB in my tests).

https://github.com/Half-Shot/matrix-appservice-discord/blob/cbd3c6797dc7ca227a20931a2a0f404b9136a557/src/store.ts#L134-L136

**Comment by turt2live** [comment]
It's safe to clear out all transactions aside from the last 10 fwiw. I also ran into a similar issue: https://github.com/turt2live/matrix-bot-sdk/issues/152
