### ISSUE TITLE
Announcements channel bridging

### ISSUE THREAD

**Issue by antonok-edm** [Half-Shot/matrix-appservice-discord#813]
**Describe the bug**
Trying to bridge the `#announcements` channel of a new Discord server doesn't work, and instead produces a generic and confusing error.

The following output appears in the logs after attempting to bridge an `#announcements` channel (identifiers modified):

```
Jul-18 03:03:34.927 [MatrixCommandHandler] error: Error bridging !MaTRIxRoOMId:homeserver.com to 112233445566778899/998877665544332211
Jul-18 03:03:34.929 [MatrixCommandHandler] error: Error: Channel "998877665544332211" not found
    at DiscordBot.<anonymous> (/src/bot.ts:488:19)
    at Generator.next (<anonymous>)
    at fulfilled (/build/src/bot.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

As a sanity-check, copy/pasting the `serverid/channelid` string from the output and pasting it after `https://discord.com/channels/` navigates to the intended channel - so it does exist.

**To Reproduce**
1. Setup the bridge on a Matrix homeserver
2. Create a new Discord server and install the appservice bot. At this point bridging normal channels should work using `!discord bridge <serverid> <channelid>`
3. Create a new Matrix room
4. Attempt to bridge the new Matrix room to the `#announcements` channel in Discord using `!discord bridge <serverid> <channelid>`

**Expected behavior**
The room should be bridged successfully. Any announcements posted to Discord should mirror to the bridged Matrix room.

Or, at least it should fail gracefully and explain that bridging an announcements channel is not supported.

**Comment by auscompgeek** [comment]
Duplicate of #774?
