### ISSUE TITLE
Application service has not registered this user 

### ISSUE THREAD

**Issue by Akselmo** [Half-Shot/matrix-appservice-discord#840]
**Describe the bug**
Bridge worked normally many weeks until at some point, it had crashed to following:

```
yarn run v1.22.19
$ yarn build && node ./build/src/discordas.js -c config.yaml
$ tsc
Aug-31 12:47:11.860 [DiscordStore] info: Starting DB Init
Aug-31 12:47:11.863 [DiscordStore] info: Filename present in config, using sqlite
Aug-31 12:47:11.864 [SQLite3] info: Opening discord.db
Aug-31 12:47:11.873 [DiscordStore] info: Database schema version is 12, latest version is 12
Aug-31 12:47:11.873 [DiscordStore] info: Updated database to the latest schema
Aug-31 12:47:12.770 [ClientFactory] info: Waiting for shardReady signal
Aug-31 12:47:13.157 [ClientFactory] info: Got shardReady signal
Aug-31 12:47:13.160 [DiscordBot] info: Discord bot client logged in.
Aug-31 12:47:13.161 [DiscordAS] info: Discordbot started successfully
Aug-31 12:47:13.165 [DiscordAS] info: Started listening on port 9005
Aug-31 12:47:53.760 [discord.js] verbose: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
Aug-31 12:47:53.917 [discord.js] verbose: [WS => Shard 0] Heartbeat acknowledged, latency of 156ms.
Aug-31 12:48:12.710 [DiscordBot] verbose: Checking bridge limits (25 active users)
Aug-31 12:48:30.288 [DiscordBot] verbose: Got incoming msg i:1014517035935481956 c:1010527251298799696 g:475097536160595979
Aug-31 12:48:30.291 [UserSync] verbose: State update requested for 68801567083462656
Aug-31 12:48:30.363 [DiscordBot] verbose: Checking bridge limits (25 active users)
Aug-31 12:48:35.012 [discord.js] verbose: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
Aug-31 12:48:35.168 [discord.js] verbose: [WS => Shard 0] Heartbeat acknowledged, latency of 156ms.
Aug-31 12:48:42.750 [DiscordBot] verbose: Checking bridge limits (25 active users)
Aug-31 12:49:16.264 [discord.js] verbose: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
Aug-31 12:49:16.423 [discord.js] verbose: [WS => Shard 0] Heartbeat acknowledged, latency of 157ms.
Aug-31 12:49:17.611 [bot-sdkAppservice] info: [ 'Processing transaction 139061' ]
Aug-31 12:49:17.613 [bot-sdkAppservice] info: [ 'Processing event of type m.room.member' ]
Aug-31 12:49:17.616 [MatrixEventProcessor] info: Skipping event due to age 70289358 > 900000
Aug-31 12:49:17.626 [bot-sdkMatrixHttpClient] error: [
  '(REQ-5)',
  { 
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_758513300764885013:matrix.akselmo.dev)'
  }
]

/root/matrix-appservice-discord/node_modules/matrix-bot-sdk/src/http.ts:110
        throw new MatrixError(errBody, response.statusCode);
              ^
Error: M_FORBIDDEN: Application service has not registered this user (@_discord_758513300764885013:matrix.akselmo.dev)
    at doHttpRequest (/root/matrix-appservice-discord/node_modules/matrix-bot-sdk/src/http.ts:110:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MatrixClient.descriptor.value (/root/matrix-appservice-discord/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:28:32)
    at MatrixClient.descriptor.value (/root/matrix-appservice-discord/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:28:32)
    at Intent.refreshJoinedRooms (/root/matrix-appservice-discord/node_modules/matrix-bot-sdk/src/appservice/Intent.ts:296:33)
    at Intent.descriptor.value (/root/matrix-appservice-discord/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:83:32)
    at Appservice.processMembershipEvent (/root/matrix-appservice-discord/node_modules/matrix-bot-sdk/src/appservice/Appservice.ts:616:9)
    at /root/matrix-appservice-discord/node_modules/matrix-bot-sdk/src/appservice/Appservice.ts:841:21
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Before crashing it sends from discord to matrix but not other way around.

**To Reproduce**
1. Launch bridge
2. Try to send something from matrix to discord
3. See error

**Expected behavior**
Message would send from matrix to discord as before.

**Comment by Akselmo** [comment]
Checking the `discord.db` file and the user `@_discord_758513300764885013:matrix.akselmo.dev` doesn't even exist in there.

**Comment by Akselmo** [comment]
Also the bot just wont get back online for some reason. Discord side bot works, Matrix side bot wont go online.

**Comment by godarklight** [comment]
I've also been getting this bug for the last few weeks - I've deleted and recreated the discord bot thinking that this was related to the discord event, which isn't the case.

It's crashing from processing m.room.member, and I noticed "[MatrixEventProcessor] info: Skipping event due to age 1638267353 > 900000"

Commenting out this early return has no effect, it still crashes. I then attempted to follow the stack trace, which crashes from inside the SDK itself, the stacktrace is exactly the same as above.

If I had to take a wild stab in the dark, https://github.com/turt2live/matrix-bot-sdk/blob/main/src/appservice/Appservice.ts#L615 is being called without registering first.

**Comment by godarklight** [comment]
This bug is the same bug as #831 - but I am using the updated discord-registration.yaml file with the domain part.

**Comment by bjornbytes** [comment]
I encountered this as well, even though my config file had the homeserver domain name in the regex.

I think the bot got into this state due a previous permission-related error that prevented a user from getting registered properly.  Afterwards, the bot would always eventually crash with the "Application service has not registered this user" error while trying to process events for the dangling user.

I managed to fix it by manually adding the user with curl (highly questionable):

```sh
curl \
  -X POST \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer [TOKEN]' \
  -d '{"type":"m.login.application_service","username":"_discord_[MISSING_USER]"}' \
  http://127.0.0.1:8008/_matrix/client/v3/register
```

This does not feel like a good solution at all though.  Maybe matrix-bot-sdk could automatically add users like this?

**Comment by Orangestar12** [comment]
The above did not work for me.
```
yarn[554021]: Jun-28 19:36:18.092 [bot-sdkMatrixHttpClient] error: [
yarn[554021]:   '(REQ-4)',
yarn[554021]:   {
yarn[554021]:     errcode: 'M_FORBIDDEN',(@_discord_[a discord bot's ID]:matrix.orangestar.dev)'
yarn[554021]:   }
yarn[554021]: ]
yarn[554021]:     error: 'Application service has not registered this user 
yarn[554021]: /home/orangestar/matrix-appservice-discord/node_modules/matrix-bot-sdk/src/http.ts:110
yarn[554021]:         throw new MatrixError(errBody, response.statusCode);
yarn[554021]:               ^
yarn[554021]: Error: M_FORBIDDEN: Application service has not registered this user (@_discord_[ID]:matrix.orangestar.dev)
```

The first time I tried the above command I got no response (which i took to mean that the operation succeeded). Subsequent attempts give me this response: `{"errcode":"M_USER_IN_USE","error":"User ID already taken."}`

**EDIT:** Erm, never mind, I appear to have more pressing issues relating to this...

![A Synapse Admin panel screenshot. The user has their domain listed twice.](https://github.com/matrix-org/matrix-appservice-discord/assets/785315/d7b5f114-c448-4b31-8706-da5f50d7dd5a)

**Comment by jam206** [comment]
Was anyone able to resolve this? I have the same issue. The bridge works at initial setup and eventually stops being online on the matrix side while throwing the following errors which cause application to crash.

```
Jul-24 09:27:51.277 [Postgres] silly: All: 
        SELECT * FROM remote_room_data
        INNER JOIN room_entries ON remote_room_data.room_id = room_entries.remote_id
        WHERE discord_channel = $discord_channel
Jul-24 09:27:51.573 [Postgres] silly: Run: INSERT INTO remote_user_guild_nicks VALUES (
                $remote_id,
                $guild_id,
                $nick
            )
Jul-24 09:27:51.575 [Postgres] silly: Run: INSERT INTO remote_user_guild_nicks VALUES (
                $remote_id,
                $guild_id,
                $nick
            )
Jul-24 09:27:51.577 [bot-sdkMatrixHttpClient] error: [
  '(REQ-13)',
  {
    errcode: 'M_FORBIDDEN',
    error: 'Application service has not registered this user (@_discord_xxx:xxx.xxx)'
  }
]

/node_modules/matrix-bot-sdk/src/http.ts:110
        throw new MatrixError(errBody, response.statusCode);
              ^
Error: M_FORBIDDEN: Application service has not registered this user (@_discord_xxx:xxx.xxx)
    at doHttpRequest (/node_modules/matrix-bot-sdk/src/http.ts:110:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MatrixClient.descriptor.value (/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:28:32)
    at MatrixClient.descriptor.value (/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:28:32)
    at Intent.refreshJoinedRooms (/node_modules/matrix-bot-sdk/src/appservice/Intent.ts:296:33)
    at Intent.descriptor.value (/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:83:32)
    at Appservice.processMembershipEvent (/node_modules/matrix-bot-sdk/src/appservice/Appservice.ts:616:9)
    at /node_modules/matrix-bot-sdk/src/appservice/Appservice.ts:841:21
```

- my regex already includes the domain.
- the user in the error does not exist in the bridge database.
- the user in the error does not exist in matrix.
