### ISSUE TITLE
Bridging broken with Dendrite 0.9.6

### ISSUE THREAD

**Issue by tux93** [Half-Shot/matrix-appservice-discord#841]
**Describe the bug**
After updating to Dendrite 0.9.6 matrix-appservice-discord no longer works and is throwing exceptions.
Also reported at [Dendrite](https://github.com/matrix-org/dendrite/issues/2690)

**To Reproduce**
1. Install Dendrite 0.9.6 and DiscordAS 3.0.0
2. Bridge some Rooms
3. Send some messages
4. For every message an exception is logged, no messages are delivered to or from Discord

**Expected behavior**
Messages are sent to and received from Discord

**Desktop (please complete the following information):**
 - OS: openSUSE
 - Browser: Firefox
 - Version: 104
 - DiscordAS 3.0.0
 - Dendrite 0.9.6
 - node 16

**Additional context**
```
Sep 01 22:36:12 node[6098]: Sep-1 22:36:12.721 [DiscordAS] error: Exception thrown while handling "room.event" event TypeError: Cannot read properties of undefined (reading 'age')
Sep 01 22:36:12 node[6098]:     at MatrixEventProcessor.<anonymous> (/home/matrix-discord/matrix-appservice-discord/src/matrixeventprocessor.ts:94:28)
Sep 01 22:36:12 node[6098]:     at Generator.next (<anonymous>)
Sep 01 22:36:12 node[6098]:     at /home/matrix-discord/matrix-appservice-discord/build/src/matrixeventprocessor.js:23:71
Sep 01 22:36:12 node[6098]:     at new Promise (<anonymous>)
Sep 01 22:36:12 node[6098]:     at __awaiter (/home/matrix-discord/matrix-appservice-discord/build/src/matrixeventprocessor.js:19:12)
Sep 01 22:36:12 node[6098]:     at MatrixEventProcessor.OnEvent (/home/matrix-discord/matrix-appservice-discord/build/src/matrixeventprocessor.js:78:16)
Sep 01 22:36:12 node[6098]:     at /home/matrix-discord/matrix-appservice-discord/src/discordas.ts:211:34
Sep 01 22:36:12 node[6098]:     at Generator.next (<anonymous>)
Sep 01 22:36:12 node[6098]:     at fulfilled (/home/matrix-discord/matrix-appservice-discord/build/src/discordas.js:5:58)
Sep 01 22:36:12 node[6098]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Half-Shot** [comment]
That sounds like we're relying on the unstable field `age`.
