### ISSUE TITLE
error: [ 'Encountered error registering user: ' ]

### ISSUE THREAD

**Issue by kc01-8** [Half-Shot/matrix-appservice-discord#905]
```
$ node ./build/src/discordas.js
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/africa/.yarn"
Oct-14 23:26:44.410 [DiscordStore] warn: Couldn't fetch schema version, defaulting to 0
Oct-14 23:26:44.462 [DiscordStore] warn: NOT backing up database while a file already exists
Oct-14 23:27:45.929 [bot-sdkMatrixHttpClient] error: [
  '(REQ-1)',
  Error: ETIMEDOUT
      at Timeout.<anonymous> (/home/africa/matrix-appservice-discord-develop/node_modules/request/request.js:848:19)
      at listOnTimeout (node:internal/timers:573:17)
      at processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    connect: true
  }
]
Oct-14 23:27:45.931 [bot-sdkAppservice] error: [ 'Encountered error registering user: ' ]
Oct-14 23:27:45.932 [bot-sdkAppservice] error: [
  Error: ETIMEDOUT
      at Timeout.<anonymous> (/home/africa/matrix-appservice-discord-develop/node_modules/request/request.js:848:19)
      at listOnTimeout (node:internal/timers:573:17)
      at processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    connect: true
  }
]
Oct-14 23:27:45.932 [DiscordAS] error: A fatal error occurred during startup: Error: ETIMEDOUT
    at Timeout.<anonymous> (/home/africa/matrix-appservice-discord-develop/node_modules/request/request.js:848:19)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7) {
  code: 'ETIMEDOUT',
  connect: true
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Happening after I run yarn start

**Comment by Mrs-Feathers** [comment]
looks like it was run with the "node" command instead of "yarn." it looks like the error is looking for the yarn executable and not finding it. you may need to run "yarn global bin" and export that as part of your path before running it again
